# Generated by Django 5.1.5 on 2025-02-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='hedline',
        ),
        migrations.AddField(
            model_name='news',
            name='headline',
            field=models.CharField(default='', max_length=200),
        ),
    ]
